[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "crjbsim"
version = "0.1.0"
description = ""
authors = ["Laurence Hole <laurence@greenvertex.dev>"]
readme = "README.md"
packages = [{ include = "src" }]